application: wjgtatistics
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.app
  
- url: /admin
  script: admin.app
#  login: admin
  
- url: /.*
  script: notfound.app